# Generated by Django 4.2.1 on 2023-05-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0002_alter_account_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("buy", "Buy Item"),
                    ("pay_bill", "Pay Bill"),
                    ("transfer", "Transfer Money"),
                ],
                default="buy",
                max_length=50,
            ),
        ),
    ]
