# Generated by Django 4.2.1 on 2023-05-21 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0003_alter_transaction_transaction_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-timestamp"]},
        ),
    ]
